from __future__ import annotations

from typing import Protocol

from app.domain.identity import Principal
from app.domain.models import Chunk, Conversation, ConversationSummary, Message


class ConversationRepository(Protocol):
    async def init_schema(self) -> None: ...
    async def ping(self) -> bool: ...
    async def create(self, session_id: str, user_id: str, title: str) -> None: ...
    async def get(self, session_id: str, user_id: str) -> Conversation | None: ...
    async def list_for_user(self, user_id: str) -> list[ConversationSummary]: ...
    async def add_message(self, session_id: str, message: Message) -> None: ...
    async def count(self) -> int: ...
    async def close(self) -> None: ...


class AnswerCache(Protocol):
    @property
    def enabled(self) -> bool: ...

    async def get(
        self, user_id: str, session_id: str, index_version: str, message: str
    ) -> tuple[str, list[dict]] | None: ...

    async def set(
        self,
        user_id: str,
        session_id: str,
        index_version: str,
        message: str,
        answer: str,
        citations: list[dict],
    ) -> None: ...

    async def set_index_version(self, version: str) -> None: ...
    async def flush_answers(self) -> int: ...


class SearchIndex(Protocol):
    def search(self, query: str, k: int = 4) -> list[tuple[Chunk, float]]: ...
    def format_for_agent(self, hits: list[tuple[Chunk, float]]) -> str: ...


class AnswerGenerator(Protocol):
    async def generate(self, query: str, index: SearchIndex) -> tuple[str, list[dict], bool]: ...


class KnowledgeLoader(Protocol):
    def load(self) -> tuple[list[Chunk], SearchIndex, str]: ...


class TokenVerifier(Protocol):
    @property
    def ready(self) -> bool: ...

    async def warmup(self) -> None: ...
    def verify(self, authorization: str | None) -> Principal: ...
